#' Problem 1
#'
#' If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#' Find the sum of all the multiples of 3 or 5 below 1000.
#' @return the sum
#' @export
problem_1 <- function() {
  multiples_sum(numbers = c(3,5), max_value = 1000)
}

#' Problem 2
#'
#' Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#' 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#' By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#'
#' @return the sum
#' @importFrom purrr map discard
#' @export
problem_2 <- function() {
  1:50 %>%
    map(fibs, 1, 2) %>%
    discard(function(x) x > 4 * 10 ** 6) %>%
    discard(function(x) x %% 2 != 0) %>%
    as.numeric() %>%
    sum()
}

#' Problem 3
#'
#' The prime factors of 13195 are 5, 7, 13 and 29.
#' What is the largest prime factor of the number 600851475143 ?
#' @return the largest prime factor
#' @importFrom numbers primeFactors
#' @importFrom purrr pluck
#' @export
problem_3 <- function() {
  primeFactors(600851475143) %>%
    pluck(max)
}

#' Problem 28
#'
#' Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:
#'
#' 21 22 23 24 25
#' 20  7  8  9 10
#' 19  6  1  2  3
#' 18  5  4  3 12
#' 17 16 15 14 13

#' It can be verified that the sum of the numbers on the diagonals is 101.
#' What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed the same way?
#' @return the sum of the numbers on the diagonals
#' @importFrom purrr discard map_dbl
#' @importFrom magrittr %>%
#' @export
problem_28 <- function() {
  N <- 1001
  even_squares <- get_squares(N, type = 'even')
  odd_squares <- get_squares(N, type = 'odd')

  down_right <- even_squares - (2*(1:500) - 1)

  up_left <- (
    odd_squares %>%
      discard(~.x == 1)
  ) - 2*(1:500)

  down_left <- even_squares %>%
    map_dbl(~.x + 1)

  sum(even_squares, up_left, down_right, down_left)
}


